services:
  - type: web
    name: coda-to-bkms-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.index:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHONPATH
        value: .
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: CODA_API_KEY
        sync: false