services:
  - type: web
    name: bkms-fastapi-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn index:app --host 0.0.0.0 --port 10000"
    workingDir: backend/api
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000