export const CONSTANTS = {
  KISHORES_CLICKED: "Kishores clicked in BKMS:",
  KISHORES_NOT_CLICKED: "Kishores not clicked in BKMS:",
  KISHORES_NOT_FOUND: "Kishores not found in BKMS:",
  SELECT_A_VALID_SUNDAY: "Select a valid Sunday",
  DATE_FORMAT: "MMMM d",
  SATURDAY_K1: "Saturday K1",
  SATURDAY_K2: "Saturday K2",
  SUNDAY_K1: "Sunday K1",
  SUNDAY_K2: "Sunday K2",
  SELECT_GROUP: "Select Group",
  YES: "Yes",
  NO: "No",
  WAS_SABHA_HELD: "Was Sabha Held?",
  WAS_P2_IN_GUJU: "Was P2 in Guju?",
  PREP_CYCLE_DONE: "2 Week Prep Cycle Done?",
  RUNNING: "Running...",
  RUN_BOT: "Run Bot",
  REQUIRED_FIELDS: "Please fill out all required fields before running the bot.",
  LONG: "long",
  NUMERIC: "numeric",
  LOCAL_URL: "http://localhost:8000",
  SOMETHING_WENT_WRONG: "Something went wrong!",
  ATTENDANCE_BOT: "BKMS Attendance Bot",
};
