export const CONSTANTS = {
  KISHORES_CLICKED: "Kishores clicked in BKMS:",
  KISHORES_NOT_CLICKED: "Kishores not clicked in BKMS:",
  KISHORES_NOT_FOUND: "Kishores not found in BKMS:",
  SELECT_A_VALID_SUNDAY: "Select a valid Sunday",
  SATURDAY_K1: "Saturday K1",
  SATURDAY_K2: "Saturday K2",
  SUNDAY_K1: "Sunday K1",
  SUNDAY_K2: "Sunday K2",
  SELECT_GROUP: "Select Group",
  YES: "Yes",
  NO: "No",
  WAS_SABHA_HELD: "Was Sabha Held?",
  WAS_P2_IN_GUJU: "Was P2 in Guju?",
  PREP_CYCLE_DONE: "2 Week Prep Cycle Done?",
  RUNNING: "Running...",
  RUN_BOT: "Run Bot",
  REQUIRED_FIELDS: "Please fill out all required fields before running the bot.",
  LONG: "long",
  NUMERIC: "numeric",
  SOMETHING_WENT_WRONG: "Something went wrong!",
  ATTENDANCE_BOT: "BKMS KM Attendance Bot",
  VALID_EMAIL: process.env.REACT_APP_VALID_EMAIL,
  VALID_PASSWORD: process.env.REACT_APP_VALID_PASSWORD,
  CANCEL: "Cancel",
  SIGN_IN: "Sign In",
  PASSWORD: "Password",
  EMAIL: "Email",
  CODA_ATTENDANCE_MISSING: "Coda attendance is currently missing. Please ensure it’s filled out before proceeding further.",
  SABHA_NOT_HELD: "Sabha was not held. Attendance marked accordingly in BKMS.",
  GOSHTHI_BOT: "BKMS Goshthi Bot",
  WAS_GOSHTHI_HELD: "Was Goshthi Held?",
  WAS_HANGOUT: "Was this a Hangout?",
  WAS_WORKSHOP: "Was a Karyakar Workshop Held?",
  BAL_MANDAL_BOT: "BKMS BM Attendance Bot",
  SATURDAY_BAL_GROUP_0: "Saturday Bal Group 0",
  SATURDAY_BAL_GROUP_1: "Saturday Bal Group 1",
  SATURDAY_BAL_GROUP_2A: "Saturday Bal Group 2A",
  SATURDAY_BAL_GROUP_2B: "Saturday Bal Group 2B",
  SATURDAY_BAL_GROUP_3: "Saturday Bal Group 3",
  SUNDAY_BAL_GROUP_0: "Sunday Bal Group 0",
  SUNDAY_BAL_GROUP_1: "Sunday Bal Group 1",
  SUNDAY_BAL_GROUP_2A: "Sunday Bal Group 2A",
  SUNDAY_BAL_GROUP_2B: "Sunday Bal Group 2B",
  SUNDAY_BAL_GROUP_3: "Sunday Bal Group 3",
};